t_PLUS    = r'\+'
t_MINUS   = r'-'
t_MULT    = r'\*'
t_DIV     = r'/'
t_MOD     = r'%'

t_EQUALS       = r'='
t_PLUSEQUALS  = r'\+='
t_MINUSEQUALS = r'-='
t_MULTEQUALS  = r'\*='
t_DIVEQUALS   = r'/='
t_MODEQUALS   = r'%='

t_EQ    = r'=='
t_NEQ   = r'!='
t_GT    = r'>'
t_LT    = r'<'
t_GTE   = r'>='
t_LTE   = r'<='

t_AND   = r'&&'
t_OR    = r'\|\|'
t_NOT   = r'!'
t_XOR = r'\^'

t_INC   = r'\+\+'
t_DEC   = r'--'

t_LSHIFT = r'<<'
t_RSHIFT = r'>>'
t_URSHIFT = r'>>>'

t_BITAND = r'&'
t_BITOR = r'\|'
t_BITNOT = r'~'
t_BITXOR = r'\^'

t_LPAREN    = r'\('
t_RPAREN    = r'\)'
t_LBRACE    = r'\{'
t_RBRACE    = r'\}'
t_LBRACKET  = r'\['
t_RBRACKET  = r'\]'
t_SEMICOLON = r';'
t_COMMA     = r','
t_DOT       = r'\.'
t_COLON     = r':'